name:                aoc2023
version:             1.0.0.0
github:              "stephenswat/aoc2023-hs"
license:             Unlicense
author:              "Stephen Nicholas Swatman"
maintainer:          "stephen@v25.nl"

dependencies:
  - base >= 4.16 && < 5
  - parsec

executables:
  aoc2023:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -Wall
      - -Wcompat
      - -O3
